# fly.toml file generated for hits on 2021-10-30T15:45:18+01:00

app = "hits"

kill_signal = "SIGTERM"
kill_timeout = 5
# processes = []

# [build]
#   image = "flyio/hellofly:latest"

[env]

[deploy]
  release_command = "/app/bin/hits eval Hits.Release.migrate"

# [experimental]
#   allowed_public_ports = []
#   auto_rollback = true

[[services]]
  # http_checks = []
  internal_port = 4000
  # processes = ["app"]
  protocol = "tcp"
  # script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    # type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
