# fly.toml file generated for gogs-demo on 2022-05-12T16:18:33+01:00

app = "gogs-demo"

kill_signal = "SIGTERM"
kill_timeout = 5

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[env]
  LOG_LEVEL = "debug"
  GOGS_URL = "gogs-server.fly.dev"
  GOGS_SSH_PORT = 10022